<a href="https://colab.research.google.com/github/Olgerd96/NeuralUniversity/blob/main/2.3_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy. Домашнее Задание. Pro

*2 балла за каждую задачу*

### Задача 1
*(2 балла)*

* Подгрузите массив с файла **iris.csv** и назовите этот массив my_array. 

* Создайте двумерный массив из случайных чисел той же размерности, что и my_array (раздел "Семплирование из распределений", потребуется использовать размерность массива my_array).

* Назовите его my_generated_array.

**Решение:**

In [ ]:
import numpy as np    # подключаем numpy
from google.colab import drive

drive.mount('/content/drive')
my_array = np.loadtxt('/content/drive/MyDrive/Colab Notebooks/Neural university/iris.csv', delimiter=',', skiprows=1) # без первой строки (заголовки)
print("Размер загруженного матрицы my_array: " + str(np.shape(my_array)))
print("\n1.1 my_array:\n"+str(my_array[0:10]))

my_generated_array = np.random.normal(my_array.mean(), my_array.mean() , np.shape(my_array))
print("\n1.2 my_generated_array (сразу после сэмплирования):\n"+str(my_generated_array[0:10]))

my_generated_array=my_generated_array.round(1) # делаем точность как у исходного массива т 1 знак после запятой :)
print("\n1.3 my_generated_array (точность как и в исходной матрице = 1 знак после запятой):\n"+str(my_generated_array[0:10]))
# на самом деле это не достаточно точный сэмпл начального массива - потому что: 
#   в начальном массиве в первом столбике был номер строки, а мы считаем это обычными данными
#   значения должны быть не отритчательные
# изучайте данные с которыми работаете!
#print("\nmy_array:\n"+str(my_array[0:,0]))

print("\nСреднее значение:\n\tmy_array = \t\t"+str(my_generated_array.mean())+"\n\tmy_generated_array = \t"+str(my_generated_array.mean()))
print("Стандартное отклонение:\n\tmy_array = \t\t"+str(my_generated_array.std())+"\n\tmy_generated_array = \t"+str(my_generated_array.std()))


Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Размер загруженного матрицы my_array: (150, 5)

1.1 my_array:
[[0.  5.1 3.5 1.4 0.2]
 [1.  4.9 3.  1.4 0.2]
 [2.  4.7 3.2 1.3 0.2]
 [3.  4.6 3.1 1.5 0.2]
 [4.  5.  3.6 1.4 0.2]
 [5.  5.4 3.9 1.7 0.4]
 [6.  4.6 3.4 1.4 0.3]
 [7.  5.  3.4 1.5 0.2]
 [8.  4.4 2.9 1.4 0.2]
 [9.  4.9 3.1 1.5 0.1]]

1.2 my_generated_array (сразу после сэмплирования):
[[ 12.99663803  -0.44561857  20.99592729  31.63038919  -1.16135567]
 [ -8.81479757  25.78387516  -1.83906012   7.94390838  26.16687155]
 [  1.38955229   8.76536192  35.59504909  10.95287487  29.57626186]
 [ -4.46892637  19.99528911  12.0156736   20.14114295  43.04460341]
 [ 38.49613819   5.29493055  46.01842859 -43.13901856  14.03330399]
 [ 16.07923041  41.12004137 -19.30783151  29.68973945  14.24657387]
 [-11.23266784   5.4427854   18.14737997  28.67637801  37.27753778]
 [ 14.24032009  20.97720586  12.18054545  19.5503

### Задача 2
*(2 балла)*

* Выполните поэлементное умножение my_array на my_generated_array (раздел "Векторные операции").

* Склейте массивы my_array, my_generated_array в один (могут помочь методы np.concatenate, np.vstack, np.hstack).

* Возьмите склеенный массив и разделите его на равные части (больше двух). Можно сделать вручную через циклы либо воспользоваться методом vsplit.

**Решение:**

In [ ]:
mult_array = my_array * my_generated_array
print("\n2.1 Поэлементное умножение двух матриц:\n"+str(mult_array[0:10]))  #вывожу не все а только 10 пераых

concatenate_arr = np.concatenate((my_array, my_generated_array))
# то же самое другой функцией: vstack_arr = np.vstack((my_array, my_generated_array))
print("\n2.2 Размер склеенной матрицы (метод concatenate): " + str(np.shape(concatenate_arr)))
print("\nМесто склейки массивов:\n"+str(concatenate_arr[len(my_array)-4:len(my_array)+6])) #len(my_array) = номер строки на которогой закончилась первая матрица

print("\n2.3 Разделенные массивы:")
split_arr = np.vsplit(concatenate_arr, 3)
for i in range(len(split_arr)):
  print("пару строк из матрицы "+str(i)+" (из "+str(len(split_arr[i]))+" элементов):\n"+str(split_arr[i][0:5]))



2.1 Поэлементное умножение двух матриц:
[[ 0.0000e+00 -2.0400e+00  7.3500e+01  4.4240e+01 -2.4000e-01]
 [-8.8000e+00  1.2642e+02 -5.4000e+00  1.1060e+01  5.2400e+00]
 [ 2.8000e+00  4.1360e+01  1.1392e+02  1.4300e+01  5.9200e+00]
 [-1.3500e+01  9.2000e+01  3.7200e+01  3.0150e+01  8.6000e+00]
 [ 1.5400e+02  2.6500e+01  1.6560e+02 -6.0340e+01  2.8000e+00]
 [ 8.0500e+01  2.2194e+02 -7.5270e+01  5.0490e+01  5.6800e+00]
 [-6.7200e+01  2.4840e+01  6.1540e+01  4.0180e+01  1.1190e+01]
 [ 9.9400e+01  1.0500e+02  4.1480e+01  2.9400e+01  1.0800e+00]
 [ 6.4000e+00  1.0120e+02  1.1745e+02 -1.6520e+01  8.6000e-01]
 [ 4.5000e+02  8.7710e+01  1.3144e+02  4.0650e+01  5.2000e+00]]

2.2 Размер склеенной матрицы (метод concatenate): (300, 5)

Место склейки массивов:
[[146.    6.3   2.5   5.    1.9]
 [147.    6.5   3.    5.2   2. ]
 [148.    6.2   3.4   5.4   2.3]
 [149.    5.9   3.    5.1   1.8]
 [ 13.   -0.4  21.   31.6  -1.2]
 [ -8.8  25.8  -1.8   7.9  26.2]
 [  1.4   8.8  35.6  11.   29.6]
 [ -4.5  20.

### Задача 3
*(2 балла)*

* Найдите все элементы массива my_array, которые больше трех и меньше 5 одновременно. Используйте методологию подвыборки массива с условием (раздел "Индексация").

**Решение:**

In [ ]:
print("3. Элементы my_array больше 3 и меньше 5:\n"+str(my_array[(my_array<5)& (my_array>3)]))
print("Всего было найдено "+str(len(my_array[(my_array<5)& (my_array>3)]))+" элементов подходящих под заданное условие")


3. Элементы my_array больше 3 и меньше 5:
[3.5 4.9 4.7 3.2 4.6 3.1 4.  3.6 3.9 4.6 3.4 3.4 4.4 4.9 3.1 3.7 4.8 3.4
 4.8 4.3 4.  4.4 3.9 3.5 3.8 3.8 3.4 3.7 4.6 3.6 3.3 4.8 3.4 3.4 3.5 3.4
 4.7 3.2 4.8 3.1 3.4 4.1 4.2 4.9 3.1 3.2 3.5 4.9 3.6 4.4 3.4 3.5 4.5 4.4
 3.2 3.5 3.8 4.8 3.8 4.6 3.2 3.7 3.3 3.2 4.7 3.2 4.5 3.1 4.9 4.  4.6 4.5
 3.3 4.7 4.9 3.3 4.6 3.9 3.5 4.2 4.  4.7 3.6 3.1 4.4 4.5 4.1 4.5 3.9 3.2
 4.8 4.  4.9 4.7 4.3 4.4 4.8 4.5 3.5 3.8 3.7 3.9 4.5 3.4 4.5 3.1 4.7 4.4
 4.1 4.  4.4 4.6 4.  3.3 4.2 4.2 4.2 4.3 4.1 3.3 4.9 4.5 3.6 3.2 3.2 3.8
 3.2 4.9 4.9 3.3 3.2 4.8 4.9 3.8 3.4 3.1 4.8 3.1 3.1 3.1 3.2 3.3 3.4]
Всего было найдено 143 элементов подходящих под заданное условие


### Задача 4
*(2 балла)*

Создайте трехмерный массив размера 2 на 3 на 4, состоящий из случайных ВЕЩЕСТВЕННЫХ чисел от 15 до 37. Используйте встроенные методы библиотеки  np.random.

**Решение:**

In [ ]:
sample_arr = np.random.uniform(low=0, high=50, size=(2,3,4))
print("4. Генерированный массив:\n"+str(sample_arr))
print("Размер матрицы sample_arr: " + str(np.shape(sample_arr)))


4. Генерированный массив:
[[[14.73121071 28.77816782 49.2014343  21.67053185]
  [33.31610338 42.02992135 26.47171701 33.52709169]
  [25.94959526 36.76047104 44.45223358 39.81549924]]

 [[49.27373051 17.07219672 30.50573382 49.01027963]
  [37.05508643 49.85683024 34.13040814 35.22028213]
  [23.59004794 46.85538262  7.04649117 10.82427807]]]
Размер матрицы sample_arr: (2, 3, 4)



### Задача 5
*(2 балла)*
Используя массив из предыдущей задачи, преобразуйте его в новый массив со следующими значениями:

    * "small", если значения меньше 20
    * "medium", если значения в промежутке [20, 30]
    * "large", если значения больше 30

**Решение:**

In [ ]:
def classify(x):
  if x< 20: return("small")
  elif x <= 30: return("medium")
  else : return("large")

condition_arr = []
for lay3d in sample_arr:
  arr2d = []
  for lay2d in lay3d:
    arr1d = []
    for x in lay2d : arr1d.append(classify(x))
    arr2d.append(arr1d)
  condition_arr.append(arr2d)
condition_arr = np.array(condition_arr)   #nympy тензор красивее на печати
print("5. Новый массив:\n"+str(condition_arr))


5. Новый массив:
[[['small' 'medium' 'large' 'medium']
  ['large' 'large' 'medium' 'large']
  ['medium' 'large' 'large' 'large']]

 [['large' 'small' 'large' 'large']
  ['large' 'large' 'large' 'large']
  ['medium' 'large' 'small' 'small']]]
